language: node_js
node_js:
- 9
sudo: false
notifications:
  email:
    on_failure: change
    on_success: change
branches:
  only:
  - master
install:
- npm install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  buildpack: nodejs
  api_key:
    secure: "$HEROKU_KEY"
  app: "$HEROKU_APP"